apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: trident-node-linux
spec:
  template:
    spec:
      containers:
        - name: csi-nodeinfo-proxy
          image: csi-nodeinfo-proxy
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /plugin
              name: plugin-dir
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - "[ -S /plugin/csi.sock ]"
            periodSeconds: 2
            failureThreshold: 30
            initialDelaySeconds: 5
        - name: trident-main
          env:
            - name: CSI_ENDPOINT
              value: unix://plugin/csi-proxy.sock
